spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8888
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
rlw:
  jwt:

    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 3600
    header: to